#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: "3.4"


services:
   tls-ca:
      image: hyperledger/fabric-ca:latest
      container_name: tls-ca
      networks:
         fabric-net:
            aliases:
               - tls-ca
            ipv4_address: 10.10.200.5
      ports:
        - "7054:7054"
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-tls
      volumes:
        - "./tls/ca:/etc/hyperledger/fabric-ca-server-tls"
      command: sh -c 'fabric-ca-server start'


   org0-ca:
      image: hyperledger/fabric-ca:latest
      container_name: org0-ca
      networks:
         fabric-net:
            aliases:
               - org0-ca
            ipv4_address: 10.10.200.10
      ports:
        - "7054:7054"
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-org0
      volumes:
        - "./org0/ca:/etc/hyperledger/fabric-ca-server-org0"
      command: sh -c 'fabric-ca-server start'


   org1-ca:
      image: hyperledger/fabric-ca:latest
      container_name: org1-ca
      networks:
         fabric-net:
            aliases:
               - org1-ca
            ipv4_address: 10.10.200.11
      ports:
        - "7054:7054"
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-org1
      volumes:
        - "./org1/ca:/etc/hyperledger/fabric-ca-server-org1"
      command: sh -c 'fabric-ca-server start'


   peer1-org1:
      image: hyperledger/fabric-peer:2.3
      container_name: peer1-org1
      networks:
         fabric-net:
            aliases:
               - peer1-org1
            ipv4_address: 10.10.200.15
      working_dir: /etc/hyperledger/fabric
      volumes:
         - /home/vagrant/shared/nodesserver/org1/peers/peer1/:/crypto
         - ./org1/peer1/data:/var/hyperledger/production
         - ./org1/peer1/home:/etc/hyperledger/fabric
         - /var/run:/host/var/run

   peer2-org1:
      image: hyperledger/fabric-peer:2.3
      container_name: peer2-org1
      networks:
         fabric-net:
            aliases:
               - peer2-org1
            ipv4_address: 10.10.200.16
      working_dir: /etc/hyperledger/fabric
      volumes:
         - /home/vagrant/shared/nodesserver/org1/peers/peer2/:/crypto
         - ./org1/peer2/data:/var/hyperledger/production
         - ./org1/peer2/home:/etc/hyperledger/fabric
         - /var/run:/host/var/run

   orderer1-org0:
      image: hyperledger/fabric-orderer:2.3.1
      container_name: orderer1-org0
      networks:
         fabric-net:
            aliases:
               - orderer1-org0
            ipv4_address: 10.10.200.20
      environment:
         - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      working_dir: /etc/hyperledger/fabric
      volumes:
         - /home/vagrant/shared/nodesserver/org0/orderers/orderer1/:/crypto
         - ./org0/orderer1/data:/var/hyperledger/production
         - ./org0/orderer1/home:/etc/hyperledger/fabric

   orderer2-org0:
      image: hyperledger/fabric-orderer:2.3.1
      container_name: orderer2-org0
      networks:
         fabric-net:
            aliases:
               - orderer2-org0
            ipv4_address: 10.10.200.21
      environment:
         - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      working_dir: /etc/hyperledger/fabric
      volumes:
         - /home/vagrant/shared/nodesserver/org0/orderers/orderer2/:/crypto
         - ./org0/orderer2/data:/var/hyperledger/production
         - ./org0/orderer2/home:/etc/hyperledger/fabric

   orderer3-org0:
      image: hyperledger/fabric-orderer:2.3.1
      container_name: orderer3-org0
      networks:
         fabric-net:
            aliases:
               - orderer3-org0
            ipv4_address: 10.10.200.22
      environment:
         - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      working_dir: /etc/hyperledger/fabric
      volumes:
         - /home/vagrant/shared/nodesserver/org0/orderers/orderer3/:/crypto
         - ./org0/orderer3/data:/var/hyperledger/production
         - ./org0/orderer3/home:/etc/hyperledger/fabric


networks:
   fabric-net:
      name: fabric-net
      ipam:
         driver: default
         config:
            - subnet: "10.10.200.0/24"



